### PR TITLE
completed css-four-column-layout exercise. - Steve Behm 

### PR DESCRIPTION
**Pull request by SteveBehm**
Screen Shot 2022-02-01 at 3 15 42 PM

### CODE REVIEW

**Review by codingcodymiller — CHANGES_REQUESTED** [review]
Hey Steve! Those icons are too big as compared to the example, and the phone images are too close to the header, please revise and submit a new screenshot with your revision

**Comment by SteveBehm** [comment]
will do thank you!

**Comment by SteveBehm** [comment]
Screen Shot 2022-02-01 at 5 53 47 PM

**Review by codingcodymiller — APPROVED** [review]
Nice work!!

**Pull request merged**
